version: 2
project_name: castkeeper
builds:
  - id: castkeeper
    binary: castkeeper
    main: ./cmd/main.go
    # env: [CGO_ENABLED=0] # SQLite requires CGO
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      pre:
        - make install
        - make pre_build
    ldflags:
      - -X github.com/webbgeorge/castkeeper.Version={{.Version}}
    tags:
      - netgo
      - osusergo
      - static_build
dockers:
  - image_templates:
      - "ghcr.io/webbgeorge/castkeeper:latest"
      - "ghcr.io/webbgeorge/castkeeper:{{ .Version }}"
      - "ghcr.io/webbgeorge/castkeeper:{{ .Major }}"
      - "ghcr.io/webbgeorge/castkeeper:{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/webbgeorge/castkeeper
      - --label=org.opencontainers.image.source=https://github.com/webbgeorge/castkeeper
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=AGPL-3.0-or-later
    extra_files:
      - castkeeper.yml.example
      - LICENSE
