services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=localdev
      - POSTGRES_USER=localdev
      - POSTGRES_DB=castkeeper

volumes:
  pgdata:
