# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

[build]
cmd = "echo 'change detected'"
full_bin = "make run"
include_ext = ["go", "templ", "js", "css", "json", "yaml"]
exclude_dir = ["web/node_modules", "web/static", "data"]
exclude_regex = ["_test\\.go", "_templ\\.go"]
