name: Test E2E

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: E2E Test
        run: |
          make install
          docker compose up -d
          make test_e2e
